server:
  port: 8883

spring:
  application:
    name: leucam-mail-service
  rabbitmq:
    addresses: amqp://***
  cloud:
    stream:
      bindings:
        userRegistrationChannel:
          destination: gassman-user-registration
        userCancellationChannel:
          destination: gassman-user-cancellation

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka

template:
  registration: "Benvenuto nel sistema Leucam Print Manager\nLa tua iscrizione e' stata correttamente effettuata con i seguenti dati : \nCognome: %s\nNome: %s\nMail: %s\n\nGrazie\nGasSMan Administrator"
  userCancellationMessage: "Ciao %s,\nIl tuo conto e' stato correttamente disattivato.\n\nGrazie\nLeucam Print Manager Administrator"
  subject:
    registration: "Leucam - Registrazione nuovo utente"
    usercancellation: "Leucam - Cancellazione utente"

mail:
  host: smtp.yourserver.org
  port:
  username:
  password:

  transport:
    protocol: smtp

  smtp:
    auth: true
    starttls:
      enable: true